#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts/
pushd bin/
sha256sum rancherd-amd64 > ../dist/artifacts/sha256sum-amd64.txt
sha256sum rancherd-arm64 > ../dist/artifacts/sha256sum-arm64.txt
popd
