name: build
on:
  push:
    branches:
    - harvester-dev
    tags:
    - v*
  pull_request:
jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest
    container:
      image: rancher/dapper:v0.6.0
    steps:
    # Git is not in Dapper container image. Add it manually for dirty check.
    - name: Add Git
      run: apk add -U git
    - name: Checkout code
      uses: actions/checkout@v4

    # Build binaries
    - name: Run dapper ci
      run: dapper ci

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/artifacts/rancherd-amd64
          dist/artifacts/rancherd-arm64
