name: build
on:
  push:
    branches:
    - harvester-dev
    tags:
    - v*
  pull_request:
jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest
    container:
      image: rancher/dapper:v0.6.0
    steps:
    # Git is not in Dapper container image. Add it manually for dirty check.
    - name: Add Git
      run: apk add -U git
    - name: Checkout code
      uses: actions/checkout@v4

    # Build binaries and SHA files
    - name: Run dapper ci
      run: dapper ci

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        gh release upload ${{ github.ref_name }} dist/artifacts/rancherd-amd64
        gh release upload ${{ github.ref_name }} dist/artifacts/rancherd-arm64
        gh release upload ${{ github.ref_name }} dist/artifacts/sha256sum-amd64.txt
        gh release upload ${{ github.ref_name }} dist/artifacts/sha256sum-arm64.txt
